site_name: Yummy Gold

theme:
  name: "material"

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav: 
  - index.md
  - Reviews.md
  - Production Process.md
  - Health Benefits.md
